#! /bin/bash

if ! type -P aocd > /dev/null; then
    echo "mkaoc: command not found: aocd"
    exit 1
fi

if [ $# -ne 2 ]; then
    echo "usage: mkaoc YYYY DD"
    exit 2
fi

AOC=~/code/python/aoc
YEAR=$(($1))
DAY=$(($2))
DEST="$AOC/$1/$2"
TEMPLATES=$AOC/extras/templates

python3 -m webbrowser https://adventofcode.com/$YEAR/day/$DAY > /dev/null
mkdir -p $DEST
if [ ! -f $DEST/a.py ]; then
    cp $TEMPLATES/a.py $DEST
    sed -i "s/D, year=YYYY/$DAY, year=$YEAR/" $DEST/a.py
    if [ ! -f $DEST/test_a.py ]; then
        cp $TEMPLATES/test_a.py $DEST
    fi
    code -r $AOC $DEST/test_a.py $DEST/a.py $DEST/input.txt
elif [ ! -f $DEST/b.py ]; then
    cp $DEST/a.py $DEST/b.py
    sed -i "s/aocd.submit(answer, part=\"a/# aocd.submit(answer, part=\"b/" $DEST/b.py
    if [ ! -f $DEST/test_b.py ]; then
        cp $DEST/test_a.py $DEST/test_b.py
        sed -i "s/from a import/from b import/" $DEST/test_b.py
    fi
    code -r $AOC $DEST/test_b.py $DEST/b.py $DEST/input.txt
fi
if [ ! -f $DEST/input.txt ]; then
    aocd $DAY $YEAR > $DEST/input.txt
fi
